### ISSUE TITLE
req is not a valid member name

### ISSUE THREAD

**Issue by NabaragRebaca** [QXIP/node-webshark#14]
I have tried to run this project in my local environment. 
sharkd is running and I have ran the apis on :8085 port. I have tested `webshark/upload` Post api and` webshark/json?req=files` Get API from postman and it seems working. 

Though I am having a problems with other Get apis like `webshark/json?req=info` I am getting following output - 

`{"jsonrpc":"2.0","id":0,"error":{"code":-32600,"message":"req is not a valid member name"}}` .

I don't understand if I am missing anything.

Also When I open the url is browser , The UI is not getting loaded. It shows something like this -
![image](https://user-images.githubusercontent.com/59081861/179704852-419aefb9-20b6-4d34-ac16-0f0cd931478f.png)

Any help would be much appreciated.

**Comment by NabaragRebaca** [comment]
hi @lmangani  . Thanks for the quick . Yes it is a local build. I have tested from the docker container and that was working. I cloned wireshark, build and ran it and trying to use it from local env.

**Comment by lmangani** [comment]
The patchset required by this application are most likely only working with the pinned versions of wireshark.

**Comment by NabaragRebaca** [comment]
Thanks. I also think due to some version compatibility issue this is not working completely. Is there any way I can check pinned versions of wireshark which will work with this. Though I haven't updated anything on package.json.

**Comment by lmangani** [comment]
> git reset --hard 640ded8e1d45ec3ee8594c385b1045cbaa0042a0   ## tested with this hash
