### ISSUE TITLE
Timestamps not preserved

### ISSUE THREAD

**Issue by bmgante** [QXIP/node-webshark#7]
Hi,

I am playing with this project and it´s quite interesting.
For test purposes i am loading only one pcap file but noticed that frame timestamps are not preserved, webshark start from zero as reference, is it possible to change it to maintain original timestamps?
Another thing, what do you recommend as process to capture traffic into captures folder? tcpdump with rotated files every minute, anything else more efficient?

![image](https://user-images.githubusercontent.com/27358817/97901021-777ab480-1d33-11eb-80ad-d6d43a5b1b22.png)

Thanks

**Comment by lmangani** [comment]
The column is showing a relative time between timestamps, and not a timestamp. I believe you can configure the columns but by default, it shows the time diff from the previous packet.
